using System;
using System.Threading;
using Microsoft.UI.Dispatching;
using Microsoft.UI.Xaml;

namespace OpenClaw.SetupPreview;

/// <summary>
/// Explicit entry point for the unpackaged WinUI 3 preview exe.
///
/// Mirrors the pattern auto-generated by EnableMsixTooling=true in MSIX
/// builds, but without requiring a Package.appxmanifest. Initializes COM
/// wrappers, installs a DispatcherQueue-backed SynchronizationContext on
/// the UI thread, then starts the WinUI Application loop with our App.
/// </summary>
internal static class Program
{
    [STAThread]
    private static int Main(string[] args)
    {
        WinRT.ComWrappersSupport.InitializeComWrappers();
        Application.Start(p =>
        {
            var dispatcher = DispatcherQueue.GetForCurrentThread();
            var context = new DispatcherQueueSynchronizationContext(dispatcher);
            SynchronizationContext.SetSynchronizationContext(context);
            _ = new App();
        });
        return 0;
    }
}
